### ISSUE TITLE
The debugger stop and quit commands do not work properly

### ISSUE THREAD

**Issue by nickbattle** [nickbattle/vdmj#21]
The intention of the stop command (and its synonym "quit") in the debugger is to drop out of the execution immediately and return to the main control prompt. That should stop all running threads too. The effect should be very similar to hitting a context exception.

Currently this doesn't work. The commands are either ignored, or put the system into a confused state.

**Comment by nickbattle** [comment]
Presumably it would be possible to improve this by actually throwing a Context exception. Migfht be worth a try...

**Comment by nickbattle** [comment]
Encountering something similar with the DAP protocol debugger. The problem seems to be that the thread that is stopped at a breakpoint is never told to die, unlike the suspended other threads that are sleeping and can be signalled to TERMINATE. I think we need something adding to the breakpoint handling to look for signals (probably on resume) and handle them for the breakpoint codepath (ie. back on the path via the Stoppoint check method). The trouble is, signal handling is currently private/protected within SchedulableThreads. I think handleSignal has to be public?

**Comment by nickbattle** [comment]
Solved roughly as above. The breakpoint return path is caught and a ThreadDeath thrown, but there was also a problem with the ConsoleDebugReader which was trying to communicate stop/quit to the threads rather than simply calling killThreads. Now fixed (in DAP and Console)

**Comment by nickbattle** [comment]
Re-opening this, after a reproducible bug report from Leo. The spec below produces the problem consistently. Note that the first stop "does nothing" and the second one crashes:
```
Initialized 1 module in 0.146 secs. 
Interpreter started
> break f
Created break [1] in 'MinimalTime' (MinimalTime.vdmsl) at line 10:9
10:             if m = 0 then
> p g(2,2)
Stopped break [1] in 'MinimalTime' (MinimalTime.vdmsl) at line 10:9
10:             if m = 0 then
MainThread> s
13:                     if n = 0 then
MainThread> s
16:                             f(m-1, f(m, n-1));
MainThread> s
Stopped break [1] in 'MinimalTime' (MinimalTime.vdmsl) at line 10:9
10:             if m = 0 then
MainThread> stop
10:             if m = 0 then
MainThread> stop
Exception in thread "DebugReader" java.util.ConcurrentModificationException
        at java.base/java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
        at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:892)
        at com.fujitsu.vdmj.debug.ConsoleDebugLink.killThreads(ConsoleDebugLink.java:231)
        at com.fujitsu.vdmj.debug.ConsoleDebugReader.doCommand(ConsoleDebugReader.java:114)
        at com.fujitsu.vdmj.debug.ConsoleDebugReader.run(ConsoleDebugReader.java:64)
nick@pollux:~> 
```
[MinimalTime.vdmsl.txt](https://github.com/nickbattle/vdmj/files/5470962/MinimalTime.vdmsl.txt)

**Comment by nickbattle** [comment]
The problem with Leo's spec is that, by having a breakpoint on "f" and then stopping at a point where you are about to recurse into "f", the signal to stop the thread was not being handled before the execution reached the breakpoint again. That made it look like multiple copies of the thread were stopped and hence you get a concurrent modification when you try to kill them (because you are already trying...).

The correction is to catch the *breakpoint* return termination signal and handle that correctly. In fact this has been done in the LSP debug link, so it's now good that both links are the same.

**Comment by nickbattle** [comment]
Fix now available.
